import "dotenv/config" // Importa o módulo dotenv para carregar as variáveis de ambiente a partir do arquivo .env. O método config() é chamado automaticamente quando o módulo é importado, o que permite acessar as variáveis de ambiente usando process.env em qualquer parte do código.
import { Pool } from "pg" // Importa a classe Pool do módulo pg, que é um cliente PostgreSQL para Node.js. A classe Pool é usada para gerenciar um pool de conexões com o banco de dados, permitindo que o aplicativo execute consultas SQL de forma eficiente e escalável.
import { PrismaPg } from "@prisma/adapter-pg" // Importa a classe PrismaPg do módulo @prisma/adapter-pg, que é um adaptador para usar o Prisma Client com o PostgreSQL. O PrismaPg é responsável por traduzir as operações do Prisma Client em consultas SQL compatíveis com o PostgreSQL, permitindo que o aplicativo interaja com o banco de dados usando a API do Prisma Client.
import { PrismaClient } from "../generated/prisma/client" // Importa a classe PrismaClient do módulo gerado pelo Prisma. A classe PrismaClient é a principal interface para interagir com o banco de dados usando o Prisma. Ela fornece métodos para realizar operações de leitura e escrita no banco de dados, como criar, ler, atualizar e excluir registros, além de suporte para transações e consultas complexas.

const pool = new Pool({ // Cria uma nova instância do Pool, que é responsável por gerenciar as conexões com o banco de dados PostgreSQL. O Pool é configurado usando um objeto de configuração, onde a propriedade connectionString é definida com a variável de ambiente DATABASE_URL, que contém a URL de conexão para o banco de dados. Essa URL inclui informações como o host, a porta, o nome do banco de dados, o usuário e a senha necessários para estabelecer a conexão com o banco de dados.
  connectionString: process.env.DATABASE_URL, // A URL de conexão para o banco de dados PostgreSQL, que é lida a partir da variável de ambiente DATABASE_URL. Essa variável deve estar definida no arquivo .env ou no ambiente de execução do aplicativo, e deve conter as informações necessárias para conectar ao banco de dados, como host, porta, nome do banco de dados, usuário e senha.
})

const adapter = new PrismaPg(pool) // Cria uma nova instância do PrismaPg, que é o adaptador para usar o Prisma Client com o PostgreSQL. O adaptador é configurado passando a instância do Pool criada anteriormente, permitindo que o Prisma Client use as conexões gerenciadas pelo Pool para executar consultas SQL no banco de dados PostgreSQL.

export const prisma = new PrismaClient({ // Cria uma nova instância do PrismaClient, que é a principal interface para interagir com o banco de dados usando o Prisma. O PrismaClient é configurado passando um objeto de configuração, onde a propriedade adapter é definida com a instância do PrismaPg criada anteriormente. Isso permite que o Prisma Client use o adaptador para traduzir as operações do Prisma em consultas SQL compatíveis com o PostgreSQL, permitindo que o aplicativo interaja com o banco de dados usando a API do Prisma Client.
  adapter, // O adaptador PrismaPg que foi criado anteriormente, permitindo que o Prisma Client use as conexões gerenciadas pelo Pool para executar consultas SQL no banco de dados PostgreSQL.
})